export const FROM_YEAR = 2021;
export const COUNTRYLIST = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegowina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo, the Democratic Republic of the",
  "Cook Islands",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia (Hrvatska)",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "France Metropolitan",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard and Mc Donald Islands",
  "Holy See (Vatican City State)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, Republic of",
  "Kuwait",
  "Kyrgyzstan",
  "Lao, People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libyan Arab Jamahiriya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia, The Former Yugoslav Republic of",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia, Federated States of",
  "Moldova, Republic of",
  "Monaco",
  "Mongolia",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia (Slovak Republic)",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "Spain",
  "Sri Lanka",
  "St. Helena",
  "St. Pierre and Miquelon",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen Islands",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan, Province of China",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Minor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna Islands",
  "Western Sahara",
  "Yemen",
  "Yugoslavia",
  "Zambia",
  "Zimbabwe",
];
export const BRAND = "DEVxDAO";
export const LICENSES = [
  {
    title: "MIT License",
    key: "0",
  },
  {
    title: "Apache License 2.0",
    key: "1",
  },
  {
    title: "BSD License",
    key: "2",
  },
  {
    title: "GPL License",
    key: "3",
  },
  {
    title: "MPL-2.0 License",
    key: "4",
  },
  {
    title: "Creative commons (for research and documents only)",
    key: "6",
  },
  {
    title: "Other",
    key: "5",
  },
];

export const GRANTTYPES = [
  "Salary and other personal compensation",
  "Travel and conferences",
  "Software, tools, infrastructure",
  "Legal, accounting, recruiting",
  "Other",
];
export const CRYPTOTYPES = {
  btc: "Bitcoin",
  eth: "Ethereum",
  casper: "Casper",
};
export const RELATIONSHIPS = [
  "I am affiliated with the ETA or a sponsor to the ETA",
  "I am a Contributor to the ETA.",
  "My Project Plan exclusively supports the business and/or activities of a Contributor of ETA.",
  "I have a close relationship with a Contributor of ETA and my Project Plan largely supports the business and/or activities of that Contributor.",
  "I am a director, officer, or employee of the ETA.",
  "None of the above",
];
export const TIMEUNITS = {
  min: "Minutes",
  hour: "Hours",
  day: "Days",
};
export const TAGS = [
  "Wallet",
  "Explorer",
  "Exchange",
  "DEX",
  "Payment System",
  "NFT",
  "Smart Contract",
  "Voting Engine",
  "Payment Processing",
  "Legal",
  "Website",
  "Registration",
  "Game",
  "Staking Tech",
  "Node Tools",
  "Community Building",
  "Marketing / Awareness",
  "Enterprise Partner",
];

export const OP_WHAT_SECTION_SIMPLE_ACTIONS = [
  "grants_update",
  "title_update",
  "short_description_update",
  "explanation_benefit_update",
  "explanation_goal_update",
  "license_update",
  "resume_update",
  "extra_notes_update",
  "is_company_or_organization_update",
  "have_mentor_update",
  "files_update",
  "total_grant_update",
  "things_delivered_update",
];

export const OP_WHAT_SECTION_COMPLICATE_ACTIONS = [
  "team_member_add",
  "team_members_add",
  "team_member_remove",
  "team_members_remove",
  "team_member_update",
  "citation_add",
  "citations_add",
  "citation_remove",
  "citations_remove",
  "citation_update",
  "milestone_add",
  "milestones_add",
  "milestone_remove",
  "milestones_remove",
  "milestone_update",
];

export const OP_WHAT_SECTION_ACTIONS = [
  ...OP_WHAT_SECTION_SIMPLE_ACTIONS,
  ...OP_WHAT_SECTION_COMPLICATE_ACTIONS,
];

export const OP_ACTIONS = {
  update: "edited",
  remove: "removed",
  add: "added",
};

export const OP_SCOPES = {
  grants: "Grants",
  files: "Files",
  title: "Title of proposed Project",
  license: "License",
  resume: "Resume",
  extra_notes: "Notes",
  team_member: "Team Member",
  team_members: "Team Members",
  milestone: "Milestone",
  milestones: "Milestones",
  citation: "Citation",
  citations: "Citations",
  short_description: "Short description of your proposed Project",
  explanation_benefit: "Explanation benefit",
  explanation_goal: "Explanation goal",
  is_company_or_organization: "Payments for this work",
  have_mentor: "Mentor",
  total_grant: "Euro amount requested",
  things_delivered: "Delivered for the DxD/ETA",
};

export const DECIMALS = 5;
export const SURVEY_PREFIX = {
  rfp: "RFP",
  grant: "S",
};

export const FORUM_REGEX = /^([A-Za-z0-9-_.]+)$/;
export const DEFAULT_API_RECORDS = 50;
